In [1]:
import torch
import random
import numpy as np
from collections import deque
from game import SnakeGameAI, Direction, Point
from model import Linear_QNet, QTrainer
from helper import plot

MAX_MEMORY = 100_000
BATCH_SIZE = 1000
LR = 0.001
block = 5

class Agent:

    def __init__(self):
        self.n_games = 0
        self.epsilon = 0 # randomness
        self.gamma = 0.9 # discount rate
        self.memory = deque(maxlen=MAX_MEMORY) # popleft()
        self.model = Linear_QNet(11, 256, 3)
        self.trainer = QTrainer(self.model, lr=LR, gamma=self.gamma)


    def get_state(self, game):
        head = game.snake[0]
        point_l = Point(head.x - block, head.y)
        point_r = Point(head.x + block, head.y)
        point_u = Point(head.x, head.y - block)
        point_d = Point(head.x, head.y + block)
        
        dir_l = game.direction == Direction.LEFT
        dir_r = game.direction == Direction.RIGHT
        dir_u = game.direction == Direction.UP
        dir_d = game.direction == Direction.DOWN

        state = [
            # Danger straight
            (dir_r and game.is_collision(point_r)) or 
            (dir_l and game.is_collision(point_l)) or 
            (dir_u and game.is_collision(point_u)) or 
            (dir_d and game.is_collision(point_d)),

            # Danger right
            (dir_u and game.is_collision(point_r)) or 
            (dir_d and game.is_collision(point_l)) or 
            (dir_l and game.is_collision(point_u)) or 
            (dir_r and game.is_collision(point_d)),

            # Danger left
            (dir_d and game.is_collision(point_r)) or 
            (dir_u and game.is_collision(point_l)) or 
            (dir_r and game.is_collision(point_u)) or 
            (dir_l and game.is_collision(point_d)),
            
            # Move direction
            dir_l,
            dir_r,
            dir_u,
            dir_d,
            
            # Food location 
            game.food.x < game.head.x,  # food left
            game.food.x > game.head.x,  # food right
            game.food.y < game.head.y,  # food up
            game.food.y > game.head.y  # food down
            ]

        return np.array(state, dtype=int)

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done)) # popleft if MAX_MEMORY is reached

    def train_long_memory(self):
        if len(self.memory) > BATCH_SIZE:
            mini_sample = random.sample(self.memory, BATCH_SIZE) # list of tuples
        else:
            mini_sample = self.memory

        states, actions, rewards, next_states, dones = zip(*mini_sample)
        self.trainer.train_step(states, actions, rewards, next_states, dones)
        #for state, action, reward, nexrt_state, done in mini_sample:
        #    self.trainer.train_step(state, action, reward, next_state, done)

    def train_short_memory(self, state, action, reward, next_state, done):
        self.trainer.train_step(state, action, reward, next_state, done)

    def get_action(self, state):
        # random moves: tradeoff exploration / exploitation
        self.epsilon = 80 - self.n_games
        final_move = [0,0,0]
        if random.randint(0, 200) < self.epsilon:
            move = random.randint(0, 2)
            final_move[move] = 1
        else:
            state0 = torch.tensor(state, dtype=torch.float)
            prediction = self.model(state0)
            move = torch.argmax(prediction).item()
            final_move[move] = 1

        return final_move


def train():
    plot_scores = []
    plot_mean_scores = []
    total_score = 0
    record = 0
    agent = Agent()
    game = SnakeGameAI()
    while True:
        # get old state
        state_old = agent.get_state(game)

        # get move
        final_move = agent.get_action(state_old)
        #print(final_move)

        # perform move and get new state
        reward, done, score, _ = game.play_step(final_move)
        state_new = agent.get_state(game)

        # train short memory
        agent.train_short_memory(state_old, final_move, reward, state_new, done)

        # remember
        agent.remember(state_old, final_move, reward, state_new, done)
        #break
        if done:
            # train long memory, plot result
            game.reset()
            agent.n_games += 1
            agent.train_long_memory()

            if score > record:
                record = score
                agent.model.save()

            print('Game', agent.n_games, 'Score', score, 'Record:', record)

            plot_scores.append(score)
            total_score += score
            mean_score = total_score / agent.n_games
            plot_mean_scores.append(mean_score)
            plot(plot_scores, plot_mean_scores)
            

pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [1]:
import pygame
pygame.display.quit() 
pygame.quit()

In [2]:


if __name__ == '__main__':
    train()

tensor([[0.1551, 0.2239, 0.0867]], grad_fn=<CloneBackward>)
0 tensor(0.2864, grad_fn=<AddBackward0>)
tensor([[0.1551, 0.2864, 0.0867]], grad_fn=<CopySlices>)
tensor([[0.1099, 0.3171, 0.0401]], grad_fn=<CloneBackward>)
0 tensor(0.2355, grad_fn=<AddBackward0>)
tensor([[0.1099, 0.3171, 0.2355]], grad_fn=<CopySlices>)
tensor([[0.1547, 0.2305, 0.1135]], grad_fn=<CloneBackward>)
0 tensor(0.2554, grad_fn=<AddBackward0>)
tensor([[0.1547, 0.2554, 0.1135]], grad_fn=<CopySlices>)
tensor([[0.1093, 0.2561, 0.1057]], grad_fn=<CloneBackward>)
0 tensor(0.2421, grad_fn=<AddBackward0>)
tensor([[0.1093, 0.2421, 0.1057]], grad_fn=<CopySlices>)
tensor([[-0.0330,  0.2577,  0.0335]], grad_fn=<CloneBackward>)
0 tensor(0.1657, grad_fn=<AddBackward0>)
tensor([[-0.0330,  0.2577,  0.1657]], grad_fn=<CopySlices>)
tensor([[0.0924, 0.1588, 0.1050]], grad_fn=<CloneBackward>)
0 tensor(0.2012, grad_fn=<AddBackward0>)
tensor([[0.0924, 0.2012, 0.1050]], grad_fn=<CopySlices>)
tensor([[-0.0214,  0.2040,  0.0374]], grad_fn=

NameError: name 'quit' is not defined

In [28]:
loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()
print(output.item())

2.8920793533325195
